apache/qpid-dispatch

- include/qpid/dispatch/amqp.h
- include/qpid/dispatch/server.h
- python/qpid_dispatch/management/qdrouter.json
- python/qpid_dispatch/management/qdrouter.policyRuleset.settings.txt
- src/connection_manager.c
- src/container.c
- src/policy.c
- src/server.c
- tests/CMakeLists.txt
- tests/system_tests_protocol_settings.py
This patch allows listener and connector settings for session capacity and for max sessions.
It does _not_ allow a setting for max-message-size. Proton does not provide an interface for changing max message size. This issue is tracked at [PROTON-1311](https://issues.apache.org/jira/browse/PROTON-1311)
Work is progressing on self tests for this feature. Proton python and wrapper interfaces tend to hide sessions and make finding session state difficult.
> DISPATCH-451: Configurable settings for session capacity and max sessions

- src/router_core/route_control.c
- src/router_core/router_core_private.h
This ensures that an autolink and linkroute can be bound to more than one
connection. The assert checking this is disabled in optimized builds and was
never triggered.
> DISPATCH-628: Multiple connections per autoLink and linkRoute overwrites connection handle

- src/policy.c
- src/policy_internal.h
Added a new parameter to methods `_qd_policy_deny_amqp_link`, `_qd_policy_deny_amqp_sender_link` and `_qd_policy_deny_amqp_receiver_link`. 
This allows to pass the correct error condition from `qd_policy_approve_amqp_sender_link` or  `qd_policy_approve_amqp_receiver_link` and send it to thew client when the link is closed.
> DISPATCH-780 - Send amqp:unauthorized-access when link is disallowed because of target / source name

- include/qpid/dispatch/amqp.h
- include/qpid/dispatch/compose.h
- include/qpid/dispatch/iterator.h
- include/qpid/dispatch/message.h
- include/qpid/dispatch/parse.h
- include/qpid/dispatch/server.h
- src/amqp.c
- src/compose.c
- src/iterator.c
- src/message.c
- src/message_private.h
- src/parse.c
- src/router_node.c
- src/server.c
- src/server_private.h
- tests/message_test.c
- tests/system_tests_two_routers.py
This PR replaces existing annotation handling with a more efficient version. It is fully compatible with 0.8.x.
It contains the same stuff as [pr171](https://github.com/apache/qpid-dispatch/pull/171) with the addition of five commits (b321fa2..50637b7) to clean up and satisfy review comments
A comparison with 0.8.x has run on a single laptop. A sender sends a short message with a varying number of 10-byte user annotations to an ingress router A. Router A sends the messages to egress router B. A single client is attached to router B. This comparison is not rigorous and at the 50-annotation-per-message level the producer started to be the limiting factor. 
Messages per second. Number of annotations, Nanno, vs router code version, 0.8.x or new.
| Nanno |   0.8.x   |  new | …
> DISPATCH-760: Message annotation handling improvements

- src/router_core/transfer.c
Some of delivery deletion requires core context and that part stays.
> DISPATCH-759: Move freeing message and iterator out of core thread

- python/qpid_dispatch/management/client.py
- python/qpid_dispatch_internal/tools/command.py
Tis fixes two issues:
- when username and password are specified in the URL they are ignored when evaluating whether SASL should be used
- When no SASL mechanism is specified the empty string passed to Proton is interpreted as "no mechs enabled". When None is used instead, Proton will select the suitable mechs automatically
> DISPATCH-737: Fix qdstat problems when only username and password are specified

- include/qpid/dispatch/buffer.h
- include/qpid/dispatch/message.h
- include/qpid/dispatch/router_core.h
- src/buffer.c
- src/message.c
- src/message_private.h
- src/router_core/connections.c
- src/router_core/forwarder.c
- src/router_core/router_core.c
- src/router_core/router_core_private.h
- src/router_core/transfer.c
- src/router_node.c
- tests/system_tests_one_router.py
- tests/system_tests_two_routers.py
1. Added new core API function qdr_deliver_continue() that will continue
delivering a large message
2. Modified qdr_link_process_deliveries() to not remove deliveries from
the undelivered list until they are fully delivered
3. Modified qd_message_receive() to recieve partial messages.
4. Modified qd_message_send() to be able to handle streaming send. This
function can now be called multiple times for the same message. It keeps
internal pointers to the point upto which the message has been sent and
is able to continue where it left off. Message content buffers are freed
as soon as the message has been sent to all recipients.
5. Added peer linkage for large settled deliveries and added a settled
list to handle with abrupt connection terminations when large messages
are being transmitted.
6. …
> DISPATCH-767 - Added code to support multi frame message streaming

- src/message.c
- src/message_private.h
Don't allow a buffer on the message buffer chain that might be removed.
Use a content-based pending buffer instead.
Don't release message lock between adding final buffer and setting
receive_complete flag.
> DISPATCH-825: Fix interlocking between message send and receive

- src/http-libwebsockets.c
- src/http.h
- src/server.c
- tests/compose_test.c
- tests/proton_utils_tests.c
These are fixes for valgrind errors in the unit tests that I saw when running tests on master. There are more to fix, in the system tests.
Requesting review as I have been away from dispatch for a while, don't want to cause a regression. ctest with my changes is no worse than without - the policy and user_id_proxy system tests are failing with timeouts for me on master with/without these changes.
> Dispatch memory fixes

- doc/book/policy.adoc
- python/qpid_dispatch/management/qdrouter.json
- python/qpid_dispatch_internal/dispatch.py
- python/qpid_dispatch_internal/management/config.py
- python/qpid_dispatch_internal/policy/policy_local.py
- python/qpid_dispatch_internal/policy/policy_manager.py
- src/dispatch.c
- src/policy.c
- src/policy.h
- tests/parse_tree_tests.c
- tests/policy-8/management-access.json
- tests/system_tests_policy.py
This adds all the code (schema, management, run time) and supporting self tests and old style doc.
This does not add anything to doc/new-book. I will coordinate that with @bhardesty
> Dispatch 990 Use patterns for policy vhost hostnames

- include/qpid/dispatch/message.h
- python/qpid_dispatch/management/qdrouter.json
- src/message.c
- src/message_private.h
- src/router_config.c
- src/router_core/agent_config_address.c
- src/router_core/agent_config_address.h
- src/router_core/connections.c
- src/router_core/core_link_endpoint.c
- src/router_core/forwarder.c
- src/router_core/route_control.c
- src/router_core/router_core.c
- src/router_core/router_core_private.h
- tests/system_tests_priority.py
Code that implements address-priority. Also changes things so that address priority takes precedence if present, otherwise defaults to message priority -- and messages now always have priority, defaulting to 4 if not specified. (Same as Proton default.)
Also a python test that tests both message and address priority.
> DISPATCH-1139 : address priority support and test

- src/policy_internal.h
Relates to DISPATCH-1009, DISPATCH-1011 which removed the implementation.
CC @ChugR
> NO-JIRA: remove unused declaration of _qd_policy_link_user_name_subst

- src/container.c
- src/router_core/delivery.h
- src/router_core/transfer.c
- src/router_node.c
- tests/system_tests_link_routes.py
Refactor the rx handler to exit early if the message is being
discarded or the delivery has already been handed to the core thread.
Avoid calling the receive code entirely if the PN_DELIVERY being read
does not contain the links current delivery.
> DISPATCH-1310: refactor the receive handler code

- README
- python/qpid_dispatch_internal/tools/command.py
- tests/CMakeLists.txt
- tests/system_tests_edge_router.py
- tests/test_command.py
- tools/qdmanage.in
- tools/qdstat.in
Main reason to migrate from optparse to argparse is python documentation itself.
- from: https://docs.python.org/2/library/optparse.html
Deprecated since version 2.7: The optparse module is deprecated and will not be developed further; development will continue with the argparse module.
- from: https://docs.python.org/2/library/argparse.html
The argparse module improves on the standard library optparse module in a number of ways including:
Handling positional arguments.
Supporting sub-commands.
Allowing alternative option prefixes like + and /.
Handling zero-or-more and one-or-more style arguments.
Producing more informative usage messages.
Providing a much simpler interface for custom type and action.
Note (from argparse doc):
- Keep in mind that what was previously called options, now …
> DISPATCH-1441: optparse to argparse migration

- console/stand-alone/README.md
- docs/books/user-guide/using-console.adoc
- python/qpid_dispatch/management/qdrouter.json
I am intentionally not mentioning the CMAKE_INSTALL_PREFIX here. I hope
people who know of it can guess that it plays a role in determining the
console installation directory.
> DISPATCH-1300 - doc default httpRootDir as being stand-alone console install path

- tests/system_tests_bad_configuration.py
The expected Linux error is
2019-10-17 10:14:09.319632 +0200 SERVER (info) [C1] Connection to unresolvable.host.name:amqp failed: proton:io Name or service not known - connect to  unresolvable.host.name:5672 (../src/server.c:974)
The expected macOS error is
2019-06-21 21:00:34.125714 -0700 SERVER (info) [C4] Connection to unresolvable.host.name:amqp failed: proton:io unknown node or service - on connect resolving unresolvable.host.name:5672 (/Users/cloud-user/projects/qpid-dispatch/src/server.c:965)
The macOS error did not match the Linux specific regex used before.
> DISPATCH-1384 - Fix assert in system_tests_bad_configuration

- CMakeLists.txt
- src/server.c
- src/timer.c
The inlining is not happening on Linux anyways, so disabling it should affect only macOS. I could not think of other way to make tests pass with the inlining, except doing some really crazy things that would have to affect what happens during normal execution too.
I have a StackOverflow question about it, btw ;)
https://stackoverflow.com/questions/56711149/how-do-i-replace-a-function-by-a-mock-implementation-when-unit-testing-a-shared
`-Wl,-export-dynamic` is Clangs equivalent of `-rdynamic` in GCC. I thought it should be used, but it does not appear to be necessary, so I am not adding that.
> DISPATCH-1384 - Fix unit_tests

- .travis.yml
- CMakeLists.txt
Now easier to do when the `matrix` key is in place in `.travis.yml`.
Doing this also fixes the duplicated top level `cache` key in `.travis.yml` we had.
It appears that `matrix` is outdated syntax, and `jobs` should be preferred, https://github.com/travis-ci/docs-travis-ci-com/issues/1500. The doc page https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix uses `matrix.include` in the text and `jobs.include` in the yaml samples. Task for another time.
> DISPATCH-1363 - Move RAT licence check from travis builds into a sub build

- python/qpid_dispatch_internal/tools/command.py
- tests/system_tests_edge_router.py
- tests/test_command.py
So, here I am just skipping the tests on rhel6 (python version < 2.7), Because the behaviour on rhel6 is just using the last option, and no error is raised.
> DISPATCH-1455: not testing mutually exclusive groups on rhel6.

- src/router_core/connections.c
- src/router_core/delivery.c
- src/router_core/forwarder.c
- src/router_core/transfer.c
Fix includes consistently adding link to proper priority slot in
connections links_with_work array.
> DISPATCH-1475: prevent I/O thread from accessing link during deletion

- src/router_core/delivery.c
This patch just adds some debug asserts and extra comments to ensure the delivery reference counts are correct (match the expectations of the code).
> DISPATCH-1544: mask coverity false positive delivery use-after-free

- src/router_core/agent.c
- src/router_core/router_core.c
- src/router_core/router_core_private.h
- src/router_core/router_core_thread.c
Refactored the core agent code by pulling out the agent fields from qdr_core_t and putting them in their own private structure with setup/cleanup methods.
> DISPATCH-1509: free core agent timer on shutdown

- src/router_core/delivery.c
- src/router_core/router_core_private.h
- src/router_core/transfer.c
Clean up the qdr_action_t anonymous union layout by moving all
delivery related action data out of the connection sub-structure and
into the delivery sub-structure.
> DISPATCH-1540: fix access to presettled flag in qdr_action_t

- python/qpid_dispatch/management/qdrouter.json
- python/qpid_dispatch_internal/management/agent.py
- tests/system_tests_bad_configuration.py
Disallow control and whitespace characters as defined by
unicodedata.category C* and Z*.
> DISPATCH-1553: disallow problematic characters in router.id attribute

- tests/system_test.py
- tests/system_tests_edge_router.py
This commit pulls the Logger class out of system_tests_edge_router and
places it into system_tests for easy access.
An example consumer of Logger is the MobileAddressTest. That test creates
a logger and loads it with facts as the test progresses but it doesn't print
anything unless there is a test failure.
By default Logger does not print to the console and it saves each log
line as it goes. When Logger is initialized either of these defaults
may be overridden.
How to print to the console with a timestamp:
from system_test import Logger
...
self.log2 = Logger(print_to_console=True, save_for_dump=False)
self.log2.log("Help I'm a Rock")
> DISPATCH-1536: Microsecond timestamp utility for self-tests

- .travis.yml
With xcode11, I saw 250s to install macports and 120s to install the ports. Much better than before.
I did not figure out how to encourage macports to use cached /opt/local/var/macports/software dir.
> DISPATCH-1384 Speed up .travis.yml by skipping unittest2 and using xcode11 with MacPorts

- include/qpid/dispatch/alloc_pool.h
- src/alloc_pool.c
- src/log.c
- src/log_private.h
If QD_MEMORY_DEBUG is defined, this stores a backtrace for each allocated pool object so that objects left unfreed can be better described at shutdown.
This is a fairly expensive feature.  We may want to consider providing an extra definable option so we can use QD_MEMORY_DEBUG without using this new feature.
> Added debug-dump backtrace for leaked objects in pooled memory.

- src/amqp.c
As suggested by @ted-ross, I am re-submitting this PR again now using getservbyname_r which is multi-thread safe.
If you find any other possible issue, please let me know.
> DISPATCH-960 - Resolving service port when using http listener

- pom.xml
Bumps apache-rat-plugin from 0.12 to 0.13.
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
> DISPATCH-1726 Bump apache-rat-plugin from 0.12 to 0.13

- src/amqp.c
- tests/c_unittests/test_amqp.cpp
The current implementation is failing with the tests in this PR in the following ways. The value `36875` is random (from reading uninitialized memory). CC @fgiorgetti 
```
$ c_unittests -r=xml -ts=* -tc=test_qd_port_int
/home/jdanek/repos/qpid/qpid-dispatch/tests/c_unittests/test_amqp.cpp:32: Failure:
CHECK(qd_port_int("0") == 0)
with expansion:
36875 == 0
/home/jdanek/repos/qpid/qpid-dispatch/tests/c_unittests/test_amqp.cpp:44: Failure:
CHECK(qd_port_int("") == -1)
with expansion:
0 == -1
/home/jdanek/repos/qpid/qpid-dispatch/tests/c_unittests/test_amqp.cpp:46: Failure:
CHECK(qd_port_int("42http") == -1)
with expansion:
42 == -1
/home/jdanek/repos/qpid/qpid-dispatch/tests/c_unittests/test_amqp.cpp:47: Failure:
CHECK(qd_port_int("http42") == -1)
with expansion:
36875 == -1 …
```
> DISPATCH-960 Handle invalid configs when resolving port

- .github/workflows/console.yaml
https://docs.npmjs.com/cli/ci.html
> DISPATCH-1720: use `npm ci` because it's appropriate and fast

- .github/workflows/build.yaml
These options are enabled in PROTON-2170 and PROTON-2171.
Proton versions that don't implement this yet will ignore them and print a CMake warning.
> NO-JIRA: Skip building Proton examples and tests in GH Action

- tests/system_tests_policy_oversize_compound.py
> Expression "(self.assertTrue(success), 'Expected router to generate close with condition: message size exceeded')" is assigned to nothing
>> https://www.deepcode.ai/app/gh/jiridanek/qpid-dispatch/5371dfbedc60fd6c429c237d7053c3e15f0d25fe/_/%2Ftests%2Fsystem_tests_policy_oversize_compound.py/python%2Fpylint%2FW0106/811/code
> NO-JIRA fix usage of self.assertTrue in policy tests

- src/adaptors/http1/http1_adaptor.c
- src/adaptors/http1/http1_client.c
- src/adaptors/http1/http1_private.h
- src/adaptors/http1/http1_server.c
- src/router_core/router_core.c
- tests/system_tests_http1_adaptor.py
DISPATCH-1791: avoid leaking qdr_delivery_t
Move the adaptor finalize prior to stopping the core thread.  This
allows the core thread to release qdr_delivery_t that were decref'ed
during the adaptor finalize code.
> DISPATCH-1816: prevent activation from running after reconnecting

- tests/system_test.py
`functools.wraps` is available in Python 2.6, I checked.
The tests mentioned in issue description do not have docstring on their own, so the docstring line is now omitted:
```
{noformat}
test 43
Start 43: system_tests_authz_service_plugin
43: Test command: /usr/bin/bwrap "--bind" "/" "/" "--bind" "/dev/zero" "/etc/nsswitch.conf" "--unshare-net" "--dev" "/dev" "--die-with-parent" "--" "/opt/hostedtoolcache/Python/3.7.9/x64/bin/python" "/home/runner/work/qpid-dispatch/qpid-dispatch/qpid-dispatch/build/tests/run.py" "-m" "unittest" "-v" "system_tests_authz_service_plugin"
43: Test timeout computed to be: 600
43: test_authorized (system_tests_authz_service_plugin.AuthServicePluginAuthzDeprecatedTest) ... ok
43: test_dynamic_source_anonymous_sender …
```
> DISPATCH-1885 Preserve test docstring in @SkipIfNeeded decorator

- include/qpid/dispatch/ctools.h
- src/remote_sasl.c
- src/router_core/modules/address_lookup_client/lookup_client.c
- src/router_node.c
- src/server.c
These are in response to fb-infer warnings of the following kind
```
/qpid-dispatch/src/router_core/core_events.c:46: error: Null Dereference
pointer `sub` last assigned on line 45 could be null and is dereferenced by call to `memset()` at line 46, column 5.
44. {
45.     qdrc_event_subscription_t *sub = NEW(qdrc_event_subscription_t);
46.     ZERO(sub);
^
47.
48.     sub->context         = context;
```
```
/qpid-dispatch/src/remote_sasl.c:72: error: Null Dereference
pointer `buffer->start` last assigned on line 71 could be null and is dereferenced by call to `memset()` at line 72, column 5.
70. {
71.     buffer->start = malloc(buffer->capacity);
72.     memset(buffer->start, 0, buffer->capacity);
^
73. }
74.
```
> NO-JIRA Use checked allocation API from DISPATCH-1685

- include/qpid/dispatch/ctools.h
Let's see what Travis thinks about this.
> DISPATCH-1900 calling calloc with zero nmemb or zero size is permitted

- .travis.yml
There is a known issue with a transitive dependency `node-fs-extra` which, starting in version 9.0.0, needs at least nodejs 10 or maybe 10.3.
https://github.com/google/docsy/issues/265 and https://github.com/jprichardson/node-fs-extra/issues/856
> DISPATCH-1750 Set nodejs version to latest LTS on Travis

- .github/workflows/build.yaml
- CMakeLists.txt
- README
This is the way LLVM configures this. It allows turning on asserts irrespective of the chosen CMAKE_BUILD_TYPE.
I read through https://stackoverflow.com/questions/22140520/how-to-enable-assert-in-cmake-release-mode/65954915 and this seemed the most straight-forward solution. I'd like to turn this on in some/most (and maybe all-except-one) CI builds.
> DISPATCH-1929 Add QD_ENABLE_ASSERTIONS CMake option to turn on asserts

- src/adaptors/http2/http2_adaptor.c
- src/router_core/connections.c
- src/router_core/delivery.c
DISPATCH-1927 - Lock link when removing the initial delivery and handle the related link_work object.
DISPATCH-1927 - Expand the scope of the lock in qdr_delivery_continue
> DISPATCH-1927

- src/http-libwebsockets.c
Needs to be reviewed and metric must have the correct suffixes, following
prometheus conventions (https://prometheus.io/docs/practices/naming/).
Please review and let me know if the approach below seems valid or not.
> DISPATCH-1586 - Added allocator metrics

- CMakeLists.txt
- cmake/FindPython.cmake
- python/CMakeLists.txt
- python/install_python.cmake
- src/CMakeLists.txt
- tests/CMakeLists.txt
The newer module can correctly configure build to use Python virtual environment,
and furthermore the PythonInterp/Libs modules have been deprecated in CMake 3.15
> DISPATCH-1942 Use findPython when on CMake3.15+

- .github/workflows/build.yaml
- cmake/RuntimeChecks.cmake
- pom.xml
- tests/lsan.supp
- tests/lsan_3rdparty.supp
This introduces build option -DSANITIZE_3RD_PARTY, defaulted to OFF. The reason is that targeted suppressions only work when the .so libraries are installed with debug symbols, which is not always the case.
Leaks are suppressed more granularly. I have already ideas about fixing some of them, but I wanted to make their suppressions explicit in this way first.
> DISPATCH-1962 Make LSan suppressions more targeted and specific

- src/http-libwebsockets.c
- src/server.c
- tests/lsan.supp
This was a silly test issue. There was no good way for the test to stop the libwebsockets server, because of how the shutdown code was structured previously. All that's needed is to stop it, and the leak disappears.
This may not be the best of fixes for it, I am open to better suggestions.
```
9: Test Case thread_tests.test_condition: PASS
9: 
9: =================================================================
9: ==10641==ERROR: LeakSanitizer: detected memory leaks
9: 
9: Indirect leak of 8397696 byte(s) in 5 object(s) allocated from:
9:     #0 0x7fb6364ee1f8 in __interceptor_realloc (/nix/store/g40sl3zh3nv52vj0mrl4iki5iphh5ika-gcc-10.2.0-lib/lib/libasan.so.6+0xad1f8)
9:     #1 0x7fb6353ebde5 in _realloc (/nix/store/yf2b40nmyhyyhlzjjniwg9a6g4w99k4s-libwebsockets-3.2.2/lib/libwebsockets.so …
```
> DISPATCH-1962 Fix leak from libwebsockets.so in unit_tests

- .github/workflows/build.yaml
CC @pwright Thanks for your suggestion, the command works. It prints the following warning, as can be seen in the GHA run
```
Failed to parse formatted text: Routers transfer messages between producers and consumers, but unlike message brokers, they do not take responsibility for messages. Instead, routers propagate message settlement and disposition across a network such that delivery guarantees are met. That is, the router network will deliver the message &ndash; possibly through several intermediate routers &ndash; and then route the consumer&#8217;s acknowledgement of that message back across the same path. The responsibility for the message is transferred from the producer to the consumer as if they were directly connected.
```
I tried to make it exit with !=0 in this situation but I …
> DISPATCH-1969 Render and archive Dispatch docu book PDF in GitHub Actions

- cmake/RuntimeChecks.cmake
- run.py.in
- tests/system_test.py
1. UBSAN is not killing the process the moment undefined behavior is detected. This is easily fixed by doing `set(RUNTIME_UBSAN_ENV_OPTIONS "halt_on_error=1 abort_on_error=1")`, but then the tests timeout all the time. Not useful.
2. UBSAN is not printing diagnostics. That is fixed by doing `set(RUNTIME_UBSAN_ENV_OPTIONS "print_stacktrace=1 print_summary=1")`
3. ASAN has extra checks that can be enabled. Enabling them does not find any new issues, so far. But it sounds like a sensible thing to turn on, for the future. `set(RUNTIME_ASAN_ENV_OPTIONS "strict_string_checks=1 detect_stack_use_after_return=1 check_initialization_order=1 strict_init_order=1")`
4. System tests don't print `.out` files produced by running routers, even if there are messages from sanitizers in them. Let's fix that. …
> DISPATCH-2030 Add additional sanitizer checks and surface router output better in tests

- .github/workflows/build.yaml
Ubuntu packages with required Proton 0.34.0 are not yet built. So the job is now failing.
> NO-JIRA: Skip the GHA Docs job until Proton 0.34.0 Ubuntu package is published

- src/dispatch.c
- src/server.c
- src/server_private.h
The HTTP server is weird, I can't find an ideal place where to stop it. It is somewhat like the adapter modules, but it is implemented differently. This here survives the Ctrl+C without a crash. I'll try to add a test. Worst case, the commit that broke this can be reverted; that would solve the problem too.
> DISPATCH-2098 - Stop HTTP server before the AMQP server

- src/router_core/modules/mobile_sync/mobile.c
- src/router_core/router_core.c
- tests/lsan.supp
This PR is simply to show that "a solution exists". I have no idea whether I am on the right track here, or not.
The original problem is
```
14: 2021-02-20 20:54:08.332325 +0100 SERVER (info) [C2] Closing connection on shutdown (../src/server.c:1377)
14: 
14: <<<<
14: 
14: Router QDR.A output file:
14: >>>>
14: 
14: =================================================================
14: ==28365==ERROR: LeakSanitizer: detected memory leaks
14: 
14: Direct leak of 56 byte(s) in 1 object(s) allocated from:
14:     #0 0x7f8503a7ce8f in __interceptor_malloc (/nix/store/g40sl3zh3nv52vj0mrl4iki5iphh5ika-gcc-10.2.0-lib/lib/libasan.so.6+0xace8f)
14:     #1 0x7f85034afd42 in qd_malloc ../include/qpid/dispatch/ctools.h:229
14:     #2 0x7f85034afd42 in qdr_core_subscribe …
```
> DISPATCH-1962 Fix leak of qdr_core_subscribe

- src/router_core/router_core.c
- tests/lsan.supp
`qdr_modules_finalize` must run before `Clean up any qdr_delivery_cleanup_t's...`.
> DISPATCH-1962 Update qdr_core_subscribe leak fix so it does not cause qdr_delivery_cleanup_t leak

- src/alloc_pool.c
- src/qd_asan_interface.h
TODO:
* does this actually do the right thing? Edit: looks right to me.
* is it necessary to instrument `unordered_move_stack` function? Edit: me thinks no, it only changes linked list metadata, it does not touch the (empty) data.
When there is a read or write to the poisoned area, the error message looks like
```
==15792==ERROR: AddressSanitizer: use-after-poison on address 0x611000034dd8 at pc 0x7fdaa75fc713 bp 0x7fff2d0c8d80 sp 0x7fff2d0c8d78
14: WRITE of size 8 at 0x611000034dd8 thread T0
14:     #0 0x7fdaa75fc712 in qd_hash_internal_remove_item /home/jdanek/repos/qpid/qpid-dispatch/cmake-build-debug-asan/../src/hash.c:131:30
14:     #1 0x7fdaa75fb51d in qd_hash_free /home/jdanek/repos/qpid/qpid-dispatch/cmake-build-debug-asan/../src/hash.c:146:13
[...]
```
> DISPATCH-2039 Poison the memory pool so that ASAN works better with it

- tools/qdstat.in
This closes #1193
(cherry picked from commit a5267f599ab00b2ca4e0c6583f0f7064ec36aa87)
> DISPATCH-2104: Fix display of plain number in qdstat

- .github/workflows/build.yaml
- CMakeLists.txt
- cmake/RuntimeChecks.cmake
- tests/tsan.supp
I decided to use Fedora in Docker instead of Ubuntu, to make the steps more similar to the CentOS; also, not splitting the builds into compile job and test job simplifies things, at the cost of having to compile everything twice (for every one of the two shards).
> DISPATCH-2120 Create GitHub Actions jobs used for gating incoming pull requests

- docs/man/CMakeLists.txt
This amends the previous commit which did not adjust all the paths correctly.
> DISPATCH-1995 Fix wrong absolute path to html doc outputs

- .github/workflows/build.yaml
This seems to be necessary for the CentOS 7 version of ctest to put errors directly into the log output. The newer versions of ctest don't seem to be affected by this added option.
See the result at https://github.com/apache/qpid-dispatch/runs/2827373458
> NO-JIRA: Run ctest with --output-on-failure, esp. on CentOS 7

- .github/workflows/build.yaml
In CI, a variable InstallPrefix is written as `“{InstallPrefix}”` instead of `“${InstallPrefix}”`.
https://github.com/apache/qpid-dispatch/blob/main/.github/workflows/build.yaml#L96 
```run: mkdir -p "${ProtonBuildDir}" "${DispatchBuildDir}" "{InstallPrefix}"```
This line creating a directory called "{InstallPrefix}". Later, while cmake build/install, creating the correct one called “INSTALL” when using the variable properly.
Link to related PR: https://github.com/apache/qpid-proton/pull/321
> Fix "${InstallPrefix}" variable in CI

- .github/workflows/build.yaml
This fixes fails such as https://github.com/apache/qpid-dispatch/pull/1290/checks?check_run_id=3029417768
```
Err:5 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libuv1-dev amd64 1.34.2-1ubuntu1.1
404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libu/libuv1/libuv1-dev_1.34.2-1ubuntu1.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
Fetched 1443 kB in 0s (12.8 MB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```
> NO-JIRA Run apt update in Actions CI, to avoid package download failures

- .travis.yml
The macOS tests exhibit only the known failure DISPATCH-2119 (and one flaky fail in one of the test runs). I'd say that PROTON-2351 is indeed resolved and newest available libuv can be again used in the tests.
> DISPATCH-2017 Use latest libuv on macOS after PROTON-2351 is resolved

- src/timer.c
This is first and the most obvious step on a journey to support compilation on the Windows OS.
> DISPATCH-2077 Replace `clock_gettime` in `qd_timer_now` with `pn_proactor_now_64` from Proton

- src/adaptors/http2/http2_adaptor.c
- tests/c_benchmarks/CMakeLists.txt
- tests/c_benchmarks/Socket.cpp
- tests/c_benchmarks/Socket.hpp
- tests/c_benchmarks/SocketException.cpp
- tests/c_benchmarks/SocketException.hpp
- tests/c_benchmarks/TCPServerSocket.cpp
- tests/c_benchmarks/TCPServerSocket.hpp
- tests/c_benchmarks/TCPSocket.cpp
- tests/c_benchmarks/TCPSocket.hpp
- tests/c_benchmarks/bm_parse_tree.cpp
- tests/c_benchmarks/bm_tcp_adapter.cpp
- tests/c_benchmarks/echo_server.cpp
- tests/c_benchmarks/echo_server.hpp
- tests/c_benchmarks/socket_utils.cpp
- tests/c_benchmarks/socket_utils.hpp
- tests/c_unittests/helpers.hpp
```
76: ------------------------------------------------------------------------------
76: Benchmark                                    Time             CPU   Iterations
76: ------------------------------------------------------------------------------
76: BM_RouterInitializeMinimalConfig           219 ms        0.214 ms            1
76: BM_AddRemoveSinglePattern                 57.0 us         57.0 us           19
76: BM_AddRemoveMultiplePatterns/1            38.9 us         38.9 us           28
76: BM_AddRemoveMultiplePatterns/3            70.8 us         70.8 us           19
76: BM_AddRemoveMultiplePatterns/10            184 us          184 us            6
76: BM_AddRemoveMultiplePatterns/30            499 us          499 us            3
76: BM_AddRemoveMultiplePatterns/100 …
```
> DISPATCH-1783 Add TCP EchoServer and Socket C++ fixtures in unittests and benchmarks

- docs/man/qdmanage.8.adoc
The spec in question is [AMQP Management v1.0 WD09](https://www.oasis-open.org/committees/document.php?document_id=54441&wg_abbrev=amqp). I managed to find a newer working draft WD12 of the spec, but I did not manage to download a readable copy of it. It looks like the spec never got past working drafts anyways.
CC @pwright
> DISPATCH-413 Reference the AMQP Management spec in docs in a less ambiguous manner

- src/container.c
This improves single-router throughput by about 8% for small message
traffic.  The extra poll picks up any output work scheduled by the
core since the last PN_CONNECTION_WAKE event.
> DISPATCH-2250: add extra poll for output after event batch

- .github/workflows/build.yaml
- .travis.yml
- src/router_core/connections.c
- src/router_core/modules/heartbeat_edge/heartbeat_edge.c
- src/router_core/router_core.c
- tests/system_test.py
- tests/system_tests_edge_router.py
This needs to be done until DISPATCH-2257 is fixed.
This closes #1422
(cherry picked from commit df03efbacd97ea44ec8d636d10d0065cbccc4611)
> NO-JIRA: bump proton stable release to 0.36.0 in CI

- .github/workflows/build.yaml
- tests/tox.ini.in
WIP: TSAN seems to crash here without any messages
```
4: Test command: /usr/bin/python3 "/__w/qpid-dispatch/qpid-dispatch/qpid-dispatch/build/tests/run.py" "unit_tests_size" "7"
4: Test timeout computed to be: 1200
1/37 Test  #4: unit_tests_size_7 .................................***Exception: SegFault  0.21 sec
```
> NO-JIRA Update GHA to Fedora 35; Add Python 3.10 tox profile

- .github/workflows/build.yaml
- .travis.yml
Defer checkin until post 1.18.0 release.
> DISPATCH-2275: restore testing of proton main branch in CI

- .gitignore
- CMakeLists.txt
- cmake/FindLibWebSockets.cmake
- python/qpid_dispatch_internal/display_name/__init__.py
- python/qpid_dispatch_internal/management/agent.py
- python/qpid_dispatch_site.py.in
- tests/system_tests_http.py
- tools/qdmanage
- tools/qdstat
There are two stages to this. First, use CMake to generate a properties file that configures the tests, and then use the file in the tests; instead of generating the py sources directly. Next, the issue itself is addressed, which is now much easier, because there is less complicated CMake logic to deal with.
> DISPATCH-2299 re-enable system_tests_http delete listeners

- .travis.yml
- tests/CMakeLists.txt
```
75: Test command: /usr/bin/tox
[...]
75: py38 create: /home/travis/build/apache/qpid-dispatch/build/tests/.tox/py38
75: ERROR: invocation failed (exit code 1), logfile: /home/travis/build/apache/qpid-dispatch/build/tests/.tox/py38/log/py38-0.log
```
> NO-JIRA use pip-installed tox instead of system-wide in Travis CI

- include/qpid/dispatch/iterator.h
- include/qpid/dispatch/message.h
- src/dispatch.c
- src/iterator.c
- src/message.c
- src/router_core/forwarder.c
- tests/c_unittests/helpers.hpp
- tests/message_test.c
- tests/run_unit_tests_size.c
- tests/system_tests_routing_protocol.py
fixes:
- buffer overflow in iterator library
- incorrect fanout value for locally destined messages
> DISPATCH-2307: prevent router failure if id is greater than 64 bytes

- src/message.c
- src/router_node.c
- tests/system_tests_log_message_components.py
o Determine the proper validation depth if message logging used
o move message logging calls to point of forwarding
o Include link-routed messages in validation
o Fail if attempting to validate after streaming buffers freed
o Extra Credit: add message rejection errors and remove dead code
> DISPATCH-2309: Ensure rx message validation succeeds before forwarding

- .github/workflows/build.yaml
- python/qpid_dispatch/management/error.py
- python/qpid_dispatch_internal/dispatch.pyi
- tests/TCP_echo_server.py
- tests/http2_server.py
- tests/http2_slow_q2_server.py
- tests/hyperh2_server.py
- tests/run_system_tests.py
- tests/system_test.py
- tests/system_tests_edge_router.py
- tests/system_tests_priority.py
- tests/system_tests_qdmanage.py
- tests/system_tests_sasl_plain.py
- tests/system_tests_ssl.py
- tests/system_tests_topology.py
- tests/system_tests_topology_addition.py
- tests/system_tests_topology_disposition.py
- tests/test_command.py
- tests/tox.ini.in
I am going to merge this on my own, because these kinds of tasks result in quite unreadable and hence unreviewable diffs. I'll try to add inline PR comments to explain what's happening, though, so you can review this later, if you want. In my experience, maintaining a proper level of sugar and possibly certain other sugar-related chemical in your bloodstream makes the work of reviewing stuff like this more bearable.
```
75: py36 run-test: commands[2] | mypy --config-file /home/jdanek/repos/qpid/qpid-dispatch/cmake-build-debug-asan/tests/tox.ini /home/jdanek/repos/qpid/qpid-dispatch/python /home/jdanek/repos/qpid/qpid-dispatch/docs /home/jdanek/repos/qpid/qpid-dispatch/tests /home/jdanek/repos/qpid/qpid-dispatch/tools /home/jdanek/repos/qpid/qpid-dispatch/cmake-build-debug-asan/python/build …
```
> DISPATCH-2321 Add mypy check for the Python code

- tests/http1_tests.py
- tests/system_test.py
- tests/system_tests_http1_adaptor.py
- tests/system_tests_http1_over_tcp.py
- tests/tox.ini.in
This has three more-or-less independent commits. I did not understand the full problem at first, so I tried to get the ports in a better way. Which I still think is worthwhile to do, but it does not fix all the fails.
Second commit avoids the daemon threads and fudge sleeps, which only obfuscate the problems and don't really do all that much good.
Third commit adds log dump to Git Hub Actions (or whenever the tests are being run by pytest). See for example https://github.com/apache/qpid-dispatch/runs/4998230289?check_suite_focus=true#step:27:703 to see what it looks like when test fails. There are logging messages from proton and from the test itself.
> DISPATCH-2323 Try binding to a port before handing it out as "free"

- README.adoc
- tests/system_test.py
Previously, the option value was parsed by splitting the string at every space character, even within quoted substrings.
* https://github.com/skupperproject/skupper-router/pull/307
> Fix `QDROUTERD_RUNNER` CMake option parsing to be shell-like (#307)

- src/python_embedded.c
This is a backport of a skupper-router fix from
* https://github.com/skupperproject/skupper-router/pull/1307
> DISPATCH-2360: call Py_Initialize before any other python C

- .github/workflows/build.yaml
https://issues.apache.org/jira/browse/DISPATCH-2363
> DISPATCH-2363: chore(gha): change Python version to match Proton requirements; Proton main needs 3.9 or greater to compile

- .github/workflows/build.yaml
https://issues.apache.org/jira/browse/DISPATCH-2363
> DISPATCH-2363: chore(gha): add the missing `build` python module, necessary for Proton to build the Python binding

- Dockerfile
Built with
```
podman build .
```
Checked that qdrouterd starts up and that qdstat and qdmanage --help works.
> DISPATCH-2357: don't clone git tips in Dockerfile, use released tags instead

- .github/workflows/build.yaml
This is a cumulative update from individual dependabot PRs.
1. less noise in git history this way
2. the upload-artifact and download-artifact actions need to be updated at the same time
3. easier to carefully review CI results for just one PR
> NO-JIRA: deps(gha): update packaged github actions versions

- .dockerignore
- Dockerfile
https://issues.apache.org/jira/browse/DISPATCH-2357
We need to use supported CentOS. In newer CentOS Streams, the PowerTools repo was renamed to crb (same name as in RHEL). Using Rocky Linux 8 seems most sensible, as we are not ready to upgrade all the way to CentOS 9 or 10.
The Dockerfile was initially intended as a help for development, not really a release artifact. If a development Dockerfile is needed, it can be added in the future.
Meanwhile, using development versions of software at random places, which then becomes part of our release tar.gz, creates bad impression and should be eliminated.
As a compromise, the Dockerfile can use the contents of the local directory for Dispatch sources. In a released tar.gz, that would be the released content, so we're fine there.
> DISPATCH-2357: fix(Dockerfile): switch to using Rocky Linux 8 as CentOS 8 is EOL

- src/alloc_pool.c
- src/dispatch.c
- src/log.c
Fixes compilation failures such as this one
```
error: call to undeclared function 'gettimeofday'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
```
> DISPATCH-2368: chore(build): add missing `#include <sys/time.h>`

- .github/workflows/build.yaml
This is a port from skupper-router of
* https://github.com/skupperproject/skupper-router/pull/401
> DISPATCH-2371: chore(gha): enable IPv6 inside Docker container to run ip6 tests

- src/dispatch.c
Fixes compilation failures such as this one
```
/builddir/build/BUILD/qpid-dispatch-1.19.0/src/dispatch.c:412:26: error: implicit declaration of function ‘getpid’; did you mean ‘getpt’? [-Wimplicit-function-declaration]
412 |     const pid_t my_pid = getpid();
|                          ^~~~~~
|                          getpt
```
from https://bugzilla.redhat.com/show_bug.cgi?id=2245601
> DISPATCH-2368: chore(build): add missing `#include <unistd.h>`

- src/router_core/modules/test_hooks/core_test_hooks.c
It's unexpected that compilers can trace the string as it flows to printf, as there are no hints in the code, but apparently they can do this nowadays.
```
error: format specifies type 'long long' but the argument has type 'long' [-Werror,-Wformat]
```
This was fixed in skupper-router in
* https://github.com/skupperproject/skupper-router/pull/1248
> DISPATCH-2368: chore(build): fix qd_log formatting placeholder

- VERSION.txt
```
File "/usr/lib/python3.12/site-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: '1.20.0-SNAPSHOT
```
This is also a known problem from skupper-router, but there it was solved by a -DVERSION build argument, without using the VERSION.txt file any more.
* https://github.com/skupperproject/skupper-router/issues/973
* https://github.com/skupperproject/skupper-router/issues/1251
> DISPATCH-2369: chore(build): set a PEP-440 compliant version to avoid a fail when building Python package
