apache/qpid-dispatch

include/qpid/dispatch/dispatch.h, router/src/main.c, src/dispatch.c, tests/run_unit_tests.c
An initial bare bones fix on the C side of the fence. Not too fancy, but doesn't allow it to go boom on empty config either.
=> DISPATCH-352 initial implementation.

tests/CMakeLists.txt, tests/system_tests_three_routers.py
second try -- deleted previous branch because it went mad and tried to take over world.
=> DISPATCH-209 : targeted sender test

doc/man/qdmanage.8.adoc, doc/man/qdrouterd.8.adoc, doc/man/qdstat.8.adoc
* Fixed typos
* Edited for consistency
* Edited and rephrased some field descriptions for clarity
=> Update qdmanage, qdrouterd, and qdstat man pages

tests/system_tests_three_routers.py
this closest-distribution test was having a problem in that none of the #2 receivers were getting any messages.  Fixed this by making explicit distinct link names for the 2 receivers on each router.
=> make all receivers get messages

include/qpid/dispatch/compose.h, python/qpid_dispatch/management/qdrouter.json, python/qpid_dispatch_internal/management/config.py, src/CMakeLists.txt, src/compose.c, src/parse_tree.c, src/parse_tree.h, src/router_config.c, src/router_core/agent_config_address.c, src/router_core/agent_config_address.h, src/router_core/connections.c, src/router_core/route_tables.c, src/router_core/router_core.c, src/router_core/router_core_private.h, src/router_private.h, tests/CMakeLists.txt, tests/parse_tree_tests.c, tests/run_unit_tests.c, tests/system_tests_qdmanage.py, tests/system_tests_two_routers.py
Passes existing tests.
Todo:
1) unit tests
2) cleanup lots of iterator->string->iterator transformations
3) doc
4) ???
5) profit!
=> Dispatch 731- configure wildcard addresses

src/router_core/router_core.c, tests/system_tests_management.py
=> DISPATCH-821: actually delete the configured address

tests/system_tests_one_router.py
First 9 Messenger tests now use reactor interface, and set self.error , etc.
I am doing a PR because I have never actually used the Messenger interface, and in some cases it's not instantly obvious how to translate Messenger concepts.  It would be nice to have someone who is familiar take a quick look...
All remaining Messenger-based tests, I have just made to 'pass', so that everything runs now. I will continue working on those.
Also, I renumbered all tests so they just go 1, 2, .... N
And gave numbers to the tests that had none.
=> DISPATCH-947 -- re-wrote first 9 Messenger tests to not use Messenger

include/qpid/dispatch/router_core.h, python/qpid_dispatch_internal/router/data.py, python/qpid_dispatch_internal/router/engine.py, python/qpid_dispatch_internal/router/mobile.py, python/qpid_dispatch_internal/router/node.py, src/router_core/connections.c, src/router_core/exchange_bindings.c, src/router_core/route_tables.c, src/router_core/router_core.c, src/router_core/router_core_private.h, src/router_pynode.c, tests/system_tests_two_routers.py
...and use that on receipt if there is no locally defined treatment
=> DISPATCH-1181: add hint about treatment to MAU 

src/router_core/connections.c, src/router_core/route_control.c, src/router_core/route_control.h, src/router_core/router_core.c
This leak is filling up the valgrind results with noise.
=> DISPATCH-1214: remove shutdown leak reported by Valgrind

include/qpid/dispatch/router.h, python/qpid_dispatch/management/qdrouter.json, python/qpid_dispatch_internal/tools/__init__.py, python/qpid_dispatch_internal/tools/display.py, src/dispatch.c, src/router_core/agent_router.c, src/router_core/agent_router.h, tests/system_tests_qdmanage.py, tools/qdstat.in
Adding Ssorj as this patch surfaces a new management entity (memoryUsage)
=> DISPATCH-1415, DISPATCH-1569: add process memory metric

src/router_core/terminus.c
As it is explained in [DISPATCH-1566](https://issues.apache.org/jira/browse/DISPATCH-1566):
"This function fails for size = 0, and ... inside it calls vsnprintf, without considering that in case of error vsnprintf returns a negative number."
So after fix we can expect this behaviour:
- (size = 0) -> safe_snprintf returns 0, and does nothing. 
- (size > INT_MAX) -> safe_snprintf returns 0, and does nothing. Since inner vsnprintf function returns int, it has no sense (and it may produce an error) to accept size > INT_MAX.
- (inner vsnprintf return value > (size -1)) -> safe_snprintf returns (size-1) -> which is the max possible value.
- (inner vsnprintf returns negative number) -> safe_snprintf returns 0. there was a parsing error.
- (inner vsnprintf return value >= 0 and < (size-1)) -> …
=> DISPATCH-1566: fix safe_snptrintf

include/qpid/dispatch/platform.h, src/CMakeLists.txt, src/platform.c, src/server.c
Phase 1: simply log the available RAM at startup.  Next phase will be to implement low memory detection.
=> DISPATCH-1572: heuristic to determine available RAM

src/message.c
DISPATCH-1579 requires this.  It includes a test case that will verify this patch
=> DISPATCH-1590: ensure msg content buffer list is valid on fanout

.travis.yml
Split out from https://github.com/apache/qpid-dispatch/pull/702
Example of log from a failed rat check https://travis-ci.org/github/apache/qpid-dispatch/jobs/661943274
=> NO-JIRA Improve printing rat check results in .travis.yml

.github/workflows/console.yaml
CC @gemmellr @kpvdr my first real GH Action (not counting the rat check)
=> DISPATCH-1720 Add GitHub Action to run console tests through npm

console/react/package.json, console/react/src/details/detailsTablePage.js, console/react/src/details/detailsTablePage.test.js, console/react/test_data/qdrService.mock.js
=> DISPATCH-1725 Fix some Jest Web Console unittests

console/react/package.json, console/react/src/connect/connect-form.test.js, console/react/src/details/createTablePage.test.js
=> DISPATCH-1725 Fix the ESLint failures

console/react/src/overview/dashboard/inflightChart.test.js, console/react/src/overview/dashboard/throughputChart.test.js
=> DISPATCH-1725 Fix the flaky tests in Jest Web Console suite

docs/books/assemblies/user-guide/configuring-network-connections.adoc, docs/books/modules/user-guide/adding-metadata-to-connections.adoc
@kgiusti could you take a look please
=> DISPATCH-1680 add openproperties doc

src/remote_sasl.c
- These changes are in PROTON-2257
=> DISPATCH-1769: Fix dispatch for Proton SASL extension API changes

.github/workflows/build.yaml, console/react/package-lock.json, console/react/package.json
Typescript is required to run eslint.
=> DISPATCH-1767 Add typescript to console dependencies

console/react/package-lock.json, console/react/package.json
I've manually tried using the console and I did not see anything broken.
=> DISPATCH-1750 Update all console deps except Patternfly and d3

.travis.yml, tests/CMakeLists.txt
=> DISPATCH-1870 Do not test gRPC if HTTP/2 support was not built

tests/system_test.py, tests/tox.ini.in
There is afaik nothing to review. I'll merge this by myself as/if needed.
=> DISPATCH-1923 Remove support for Python 3.5

tests/lsan.supp
leak:qd_message_receive and leak:_flush_send_queue_CT can be now removed
=> DISPATCH-1962 Remove outdated entries in lsan.supp

docs/books/modules/user-guide/connecting-using-mutual-ssl-tls-authentication.adoc, docs/books/modules/user-guide/enabling-ssl-tls-encryption.adoc, docs/books/modules/user-guide/securing-connections-between-routers.adoc
as suggested by @kgiusti (ref ENTMQIC-2950)
=> update definition of cacertfile

docs/books/modules/user-guide/connecting-routers-external-amqp-containers.adoc, docs/books/modules/user-guide/connecting-routers.adoc, docs/books/modules/user-guide/listening-client-connections.adoc, docs/books/modules/user-guide/setting-up-access-web-console.adoc
=> NO-JIRA clarify symbolic service name in docs

.travis.yml, LICENSE, pom.xml, src/qd_asan_interface.h, tests/CMakeLists.txt, tests/c_unittests/CMakeLists.txt, tests/c_unittests/c_unittests_main.cpp, tests/c_unittests/qdr_stubbing_probe.cpp, tests/c_unittests/qdr_stubbing_probe.hpp, tests/c_unittests/test_terminus.cpp, tests/cpp-stub/CMakeLists.txt, tests/cpp-stub/LICENSE.txt, tests/cpp-stub/addr_any.h, tests/cpp-stub/addr_pri.h, tests/cpp-stub/cpp_stub.h, tests/cpp-stub/elfio.hpp
This brings forward elements of https://github.com/apache/qpid-dispatch/pull/853 and https://github.com/apache/qpid-dispatch/pull/880.
=> DISPATCH-1783 add cpp-stub unittest mocking/stubbing tool

tests/c_unittests/CMakeLists.txt, tests/c_unittests/c_unittests_main.cpp
I've checked this with Irina's job. It seems to pass.
=> DISPATCH-2328: detect _FORTIFY_SOURCE in c_unittests and bail out

.github/workflows/build.yaml
* https://github.com/skupperproject/skupper-router/issues/1317
* https://github.com/skupperproject/skupper-router/pull/1318 
(cherry picked from commit ba8b33194f003e5fe01dd81d72c3b2b4dcb8b0ed)
=> DISPATCH-2364: Cherry-pick from skupper-router: "Fixes #1317 - Define `${BuildType}` in GitHub Actions jobs (#1318)"

.github/workflows/build.yaml
https://issues.apache.org/jira/browse/DISPATCH-2365
=> DISPATCH-2365: chore(gha): patch up the CentOS 7 job so that it runs again
